import { useMemo, useState } from 'react';
import { motion } from 'framer-motion';
import { characters } from '../../data/gameData';
export default function CharacterScreen({ onSelect }) {
  const [currentIndex, setCurrentIndex] = useState(null);
  const [selected, setSelected] = useState(null);
  const [drawing, setDrawing] = useState(false);
  const preview = useMemo(() => (drawing && currentIndex !== null ? characters[currentIndex] : selected), [currentIndex, drawing, selected]);
  const handleDraw = () => {
    setDrawing(true); setSelected(null); let count = 0;
    const interval = setInterval(() => { setCurrentIndex(count % characters.length); count += 1; if (count > 14) { clearInterval(interval); const finalCharacter = characters[Math.floor(Math.random() * characters.length)]; setSelected(finalCharacter); setDrawing(false); } }, 120);
  };
  return <div className="min-h-screen flex items-center justify-center p-4" style={{ background: 'linear-gradient(135deg, #78350f 0%, #92400e 30%, #b45309 60%, #d97706 100%)' }}><motion.section initial={{ opacity: 0, y: 24 }} animate={{ opacity: 1, y: 0 }} className="max-w-xl w-full glass rounded-[2rem] overflow-hidden"><header className="p-6 text-center text-white" style={{ background: 'linear-gradient(135deg, #92400e, #d97706)' }}><p className="text-xs font-black uppercase tracking-[0.2em] text-amber-100">Passo 1</p><h2 className="text-3xl font-black mt-2">Sorteie seu personagem</h2><p className="text-amber-100 text-sm mt-2">Na vida real, as pessoas não começam do mesmo lugar.</p></header><div className="p-6 space-y-5"><div className="rounded-3xl border-2 border-dashed border-amber-200 bg-amber-50 min-h-[18rem] p-6 text-center flex flex-col items-center justify-center">{preview ? <><div className="text-6xl mb-3" aria-hidden="true">{preview.emoji}</div><h3 className="text-2xl font-black text-slate-900">{preview.name}</h3><span className="inline-flex mt-2 rounded-full px-4 py-1 text-white font-black text-sm" style={{ backgroundColor: preview.levelColor }}>{preview.level}</span><p className="text-sm text-slate-700 leading-6 mt-4">{preview.description}</p><ul className="mt-4 flex flex-wrap gap-2 justify-center text-xs font-semibold text-slate-700">{preview.advantages.map((advantage) => <li key={advantage} className="bg-white rounded-full border px-3 py-1">{advantage}</li>)}</ul></> : <><div className="text-6xl opacity-30 mb-3" aria-hidden="true">🃏</div><p className="text-slate-500">Clique para descobrir uma trajetória possível.</p></>}</div><div className="flex gap-3"><button aria-label="Sortear personagem" onClick={handleDraw} disabled={drawing} className="flex-1 rounded-2xl bg-amber-700 hover:bg-amber-800 disabled:opacity-60 text-white font-black px-5 py-4 transition-colors">{drawing ? 'Sorteando...' : 'Sortear personagem'}</button><button aria-label="Iniciar partida com personagem sorteado" onClick={() => selected && onSelect(selected)} disabled={!selected || drawing} className="flex-1 rounded-2xl border border-amber-300 bg-white text-amber-900 font-black px-5 py-4 hover:bg-amber-50 disabled:opacity-50 transition-colors">Jogar</button></div></div></motion.section></div>;
}